### ISSUE TITLE
Documenting J2ObjC compile within Xcode

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#299]
There are some situations, particularly debugging, where it would be preferable to do the ObjectiveC compile within Xcode. This requires flattening the translated files to a single directory. The benefits of this are:

1. Faster iteration cycle as it's only building a single required 
1. Better debugging by making breakpoints work

**Comment by confile** [comment]
@advayDev1 @brunobowden  What about the configuration in this case. Do I have to configure Xcode myself or is it done automatically like with cocoapods?

**Comment by brunobowden** [comment]
Automatic configuration. This is a long term issue, nothing that will be
worked on now.

**Comment by advayDev1** [comment]
I believe we stated in another bug that we explicitly do not want to support two build paths as one is enough.  We'd never be able to get them to match up in flags, incrementality, etc.

Note it is already possible to have your 'run' button in Xcode also do the j2objc translation for you (I already do this).  Just 1) create an 'External Build System' target in Xcode and have it run the appropriate Gradle command __making sure__ that you do not check the box that shares environment variables with external command and 2) have your iOS app have a 'target dependency' on that External Build System target.  Voila, each time you click build you get the latest Java code too.  I think this is the best way to go because it gives the same bits as if you ran gradle yourself.  We could expand it to for example just run the single architecture you want by passing some sort of argument (?).

**Comment by brunobowden** [comment]
@advayDev1 - can you document this in the FAQ, then we'll call it a day.

**Comment by advayDev1** [comment]
Ok then duping to #298
