### ISSUE TITLE
Avoid slowing down Android Studio build

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#334]
When an Android Studio build is done, it now results in running the J2ObjC Plugin build, even though it isn't used. I've confirmed this by deleting the shared/build folder and then building my Android app. The build ends up being much slower, hence an irritating system.

Unless there's another alternative, I think we should consider stop making the Java plugin 'build' task dependent on the J2ObjC build. For the plugin to depend on the Java plugin is fine. Instead, we'd just use the existing `j2objcBuild` task. If you want to build both, then specify both on the command line.

**Comment by brunobowden** [comment]
@advayDev1, @confile - I'd like both of your opinions on this

**Comment by confile** [comment]
What do you mean by that: 

> If you want to build both, then specify both on the command line.

Anyway there should be some option to disable j2objc translation.

**Comment by advayDev1** [comment]
I disagree.  'build' is a part of the lifecycle plugin, not specific to Java - it means build the project, all of it.  If a project for example contains java and c++, build will build the c++ too, which is entirely analogous to our plugin.

what's more important though is that I cannot reproduce @brunobowden your behavior.  The Android plugin for gradle, when deploying an Android app to a device for testing, for me only builds nameOfAndroidProject:assembleDebug as far as I can tell, which if your gradle setup is correct, will only build the android project and all of its Java dependencies.  It should never run shared:build at all.  Never when I test on my android device does it do the substantial j2objc builds for all of my projects.

If you've customized your android run configuration in Android Studio to run 'build' (instead of androidProject:assembleDebug'), then that is expected behavior I guess.

**Comment by advayDev1** [comment]
to be clear my disagreement was with @brunobowden 's original post.  @confile , there is already a way to do this: http://www.practicalgradle.org/blog/2010/10/skipping-tasks/

**Comment by advayDev1** [comment]
@brunobowden  - assigning back for your comment since both of us have given our views.

**Comment by brunobowden** [comment]
I changed the build to "android:assembleDebug" and it's now working correctly... so closing this.

Previously Android Studio had the setting for "Gradle-aware Make". I think it's from some very old defaults in the app. Now when I do the build, I only see the `j2objcHackToForceCompilation`, which is expected from the apply.

**Comment by advayDev1** [comment]
pasting here to upload an image

<img width="664" alt="screen shot 2015-08-01 at 7 14 09 pm" src="https://cloud.githubusercontent.com/assets/11729521/9024382/95a511a4-3881-11e5-8525-9e4256990614.png">
