### ISSUE TITLE
Verify working build without J2ObjC default libs

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#428]
@advayDev1 - can you experiment doing a build with any default libs except for jre_emul? So that it downloads Guava, JUnit, Mockito and builds them all locally? That's an important stepping stone for @tomball to publish J2ObjC releases that don't include these libraries.

@tomball - does it make sense to publish j2objc_annotations as a proper jar on MavenCentral, similar to javax.inject and jsr305?

**Comment by advayDev1** [comment]
@brunobowden:
i think a better solution is to set up a j2objc-contrib/j2objc-common-libs-e2e-test project.
This project would be just like our systemTests directory but would have a separate test for each common library we want to ensure is always building.  I think we need to split it from this project because the tests may take a very long time.  This core repository would be a git submodule into the e2e tests one, and we could update it whenever one of us feels like a major change has been made.

Thoughts?

j2objc_annotations is already on MavenCentral fyi.

**Comment by advayDev1** [comment]
@brunobowden and @tomball, I've sent a proposal here:
https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test/issues/1

Once I get this up and running and building the libraries mentioned above and possible some other common ones, I'll send an email to j2objc-discuss asking for libraries folks would like included.

**Comment by advayDev1** [comment]
We're not even close to building say Guava locally.

With the following build:
```gradle
dependencies {
    compile 'com.google.j2objc:j2objc-annotations:0.9.8'
    compile 'com.google.code.findbugs:jsr305:3.0.0'
    compile 'com.google.errorprone:error_prone_annotations:2.0.4'
    compile 'org.codehaus.mojo:animal-sniffer-annotations:1.14'
    j2objcTranslation 'com.google.guava:guava:19.0-rc1:sources'
}

j2objcConfig {
    filenameCollisionCheck false
    autoConfigureDeps true
    // Almost always there are no tests provided in an external source jar.
    testMinExpectedTests 0
    finalConfigure()
}

```

We get the following compile errors: https://gist.github.com/advayDev1/04196894d0a6291294d5

**Comment by brunobowden** [comment]
I'd missed this was `19.0-rc1`... it'll take time but we'll get there eventually.

**Comment by advayDev1** [comment]
This work is now happening in the other repo linked above.
