### ISSUE TITLE
Faster Xcode build: smaller default set for enabledArchs

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#443]
During development state doing ``gradle shared:j2objcXcode`` for working with code changes in the Xcode project appears to be very slow. Even changing a single line and doing incremental compile takes about 2 minutes for my project. With the old version of this plugin I could do it in 3 to 5 seconds which is much more acceptable. 

Here is what I propose. During development stage it does not seems to be necessary to generate a pre compiles lib from your translated code. We should introduce a flag: 

```
fastDevelopment = true
``` 
When this flag is set the plugin translates the code and the ``j2objcXcode`` task adds the translated sources to the pod in Xcode. 

This makes development super fast. I myself worked this way with the old plugin for a while. 

@advayDev1 @brunobowden Looking forward to your comments on this.

**Comment by advayDev1** [comment]
the j2objcXcode task does not currently set anything up that would allow xcode to compile the translated source, it only support linking into the libraries made by the plugin and include the headers so generated.

or were you suggesting we should add such a feature as part of fastDevelopment = true?

also, have you tried using the existing documentation on how to speed up a build?  at the end of the day compiling the Objective C into libraries should be no faster in Xcode GUI than Gradle, since Gradle just executes Clang like Xcode; Gradle also parallelizes the Clang calls depending on the number of cores/CPUs you have.  However, Xcode may well be building only the debug version and only the current architecture you are using, for which we provide the j2objc.enabledArchs=(XX) and j2objc.releaseEnabled=false flags you can set in local.properties.  Please set those flags and then indicate how long it is taking.

HOWEVER, if you use --build-closure, and change just one Java file, it is correct that everything gets retranslated.  There is no guaranteed correct method to retranslate less than every file.  The old plugin was faster here, because it had a code defect that just retranslated that one file that changed.  If you choose not to use --build-closure, you can indeed have much faster retranslation and thus faster builds overall.

**Comment by confile** [comment]
@advayDev1 

> the j2objcXcode task does not currently set anything up that would allow xcode to compile the translated source, it only support linking into the libraries made by the plugin and include the headers so generated.

> or were you suggesting we should add such a feature as part of fastDevelopment = true?

Yes this feature should be part of fastDevelopment = true. It should be similar to the j2objcXcode task of the old plugin.

> j2objc.enabledArchs=(XX) 

Are all other archs being disabled when I set this flag? How do I know which architecture I have to choose? Lets say I want to run my app on the simulator iPhone6 ios 8.1 what is the correct arch. May be you could provide a list of archs in the FAQ?

**Comment by confile** [comment]
> HOWEVER, if you use --build-closure, and change just one Java file, it is correct that everything gets retranslated. There is no guaranteed correct method to retranslate less than every file. The old plugin was faster here, because it had a code defect that just retranslated that one file that changed. If you choose not to use --build-closure, you can indeed have much faster retranslation and thus faster builds overall.

May be we should include this faulty translation in fastDevelopment = true

**Comment by confile** [comment]
@advayDev1 When I need ``build-closure`` do you see a way to omit it?

**Comment by brunobowden** [comment]
It's a substantial increase in complexity to support two different but similar build systems. The existing translate/package step and also a new in Xcode build step. It's hard to get two systems to have the same consistent behaviour as is essential in any build system. The FAQ entry that I published in #444 seems the best solution for now. I think it's more important that we build out support for dependencies and ease of adoption (as @advayDev1 is doing). Then afterwards we can ponder this again. You are of course welcome to try developing something like this... but also supporting the dependencies that we're also doing is going to make it very involved.

**Comment by advayDev1** [comment]
See my comments on the PR.  What you want to do is reduce the default supported archs.
We should not be touching enabled archs - that is for the user to configure alone.
