### ISSUE TITLE
Podspecs output should be build/j2objcOutputs directory

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#549]
We should not put any files in project/build/.  They should be in project/build/something.

**Comment by advayDev1** [comment]
Hmm I guess we've always done this?

https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/PodspecTask.groovy#L80

I've never had it happen to my project since j2objcPodSpec never ran for me

**Comment by advayDev1** [comment]
Not holding 0.5 on this.

Should move to build/j2objcOutputs/podspecs.

**Comment by brunobowden** [comment]
You mean `build/j2objcOutputs/`, rather than a further `podspecs` subdirectory?

**Comment by advayDev1** [comment]
no, build/j2objcOutputs/podspecs is what i mean

**Comment by brunobowden** [comment]
Turns out that you can't output to `j2objcOutputs/podspec` as podspecs aren't permitted to have a relative path that traverses the parent:

_Podspecs should be located at the root of the repository, and paths to files should be specified relative to the root of the repository as well. File patterns do not support traversing the parent directory ( .. ). File patterns may contain the following wildcard patterns:_

https://guides.cocoapods.org/syntax/podspec.html#group_file_patterns

I'm a little shocked at this but it would explain why an earlier version wasn't working for me. As an alternative, I've set it to output to build/j2objcOutputs instead.

**Comment by advayDev1** [comment]
Interesting security conscious limitation actually...  I guess we have no choice.

**Comment by brunobowden** [comment]
Interesting thought... you think the security concerns drove the limitation?

**Comment by advayDev1** [comment]
I'd bet on it.  Nice way to prevent a podspec from breaking out of their form of a chroot jail.  That would explain both the inability to use absolute paths and the lack of `..`

**Comment by brunobowden** [comment]
I can use absolute paths for certain things, e.g. the j2objc libraries.
Knowing Cocoapods there's probably a lot going on inside that may not all
make sense.
