### ISSUE TITLE
Unable to include resources for unit tests run via the test runner binary

### ISSUE THREAD

**Issue by dpuryear** [j2objc-contrib/j2objc-gradle#80]
The j2objc documentation describes how to includes resources within an Xcode project at https://github.com/google/j2objc/wiki/Java-Resources and explains why it is necessary when using package prefixes and reflection calls like Class.forName.  However, the converted tests generated by this gradle plugin are run via a test runner binary and there doesn't appear to be a way to include that package prefix resource in order for those tests to pass.  I'm using mockito because it is already included and translated by j2objc but some of the calls when setting up mocks use Class.forName and those are failing, presumably because of the package prefix issue described on the wiki page referenced above.

Are there any alternatives other than not using mocks for the tests?

**Comment by brunobowden** [comment]
Hi @dpuryear, the plugin has undergone a big improvement over the last two months. Just recently I got the resources working end to end in both unit tests and loading within Xcode. I extensively use package prefixes, so that shouldn't be an issue either.

I'm going to mark this issue as closed but please try it again after #320 is committed, or when the 0.4.0 release is made over the next few days. If you still have an issue please reopen this bug or write a new one as appropriate.
