### ISSUE TITLE
Style Guidelines for CONTRIBUTING.md

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#97]
Start developing style guidelines for the project. Ideally based of some existing style guidelines, which are extended for this particularly use case.

- return statements
- project.j2objcConfig access and @Input and @Output connections
- project.with

**Comment by advayDev1** [comment]
Here's the standard Groovy style guide:
http://www.groovy-lang.org/style-guide.html

Since we are a 100% groovy project, I think we should stick as closely as we can to them.  A mixed Java/Groovy style I think will be even more confusing.

**Comment by brunobowden** [comment]
Looks good, we should follow this and then add extra stuff specific to Gradle. I'll work on that.

**Comment by advayDev1** [comment]
Ah good point.

**Comment by advayDev1** [comment]
Suggest we say that our style is Groovy style guide, and where it does not specify and does not conflict, back-off to Google Java style guide:
https://google-styleguide.googlecode.com/svn/trunk/javaguide.html

Also, we need to make a decision on top-level method calls in statements.  We are very inconsistent between `java.call(arg)` style and `groovy.call arg` style.

**Comment by brunobowden** [comment]
I personally prefer parentheses as I find it more familiar. It sounds like the Groovy Style Guide isn't clear on this but I suspect it would make it easier for other engineers contributing.

What's your thoughts on this @advayDev1?

**Comment by advayDev1** [comment]
I'm torn.  I'm huge on consistency so that style things become more mechanical and less subject to reviewer dispute.  If we're going to split into parens and no-parnes, I'd suggest the following rules:

1.  If the statement is solely a DSL/property setting method (ex. 'translateArgs in j2objcConfig'), do not use parentheses on the top-level method.
1.  If the statement is a logging method of the form logger.LEVEL or log.LEVEL, do not use parentheses on the top-level method.
1.  Otherwise, always use parentheses.

Thoughts?
